Accept Absolute Path in 'repoPath'
woolfg/dokuwiki-plugin-gitbacked pull request #81
Opened 2022-08-12 08:33 UTC by sjv0

Don't concatenate DOKU_INC and repoPath if repoPath is an absolute path.

2022-08-12 08:41 UTC, woolfg commented
discussion see #80

2022-08-12 08:58 UTC, woolfg requested changes
looks good, we just have to think if we want to support Windows as well? @mhoffrog any thoughts on that? what is your opinion @sjv0?

2022-08-12 08:58 UTC, woolfg commented on action/editcommit.php
> +        if (!defined('DOKU_FARM') && $repoPath[0] !== '/') {
- I would use `!== DIRECTORY_SEPARATOR`
- what about empty paths? should we consider empty/null as `.`? @mhoffrog ?
- do we have to consider Windows as well? then we have to check something like `preg_match('~\A[A-Z]:(?![^/\\\\])~i',$path) > 0` (copied from stack overflow)

2022-08-12 11:23 UTC, mhoffrog commented on action/editcommit.php
> +        if (!defined('DOKU_FARM') && $repoPath[0] !== '/') {
@woolfg @sjv0 I'd prefer to support Windows as well. So I'd prefer to check with PHP absolute path function, if the config value of the path is equal to the PHP converted absolute path name.

2022-08-12 11:33 UTC, woolfg commented on action/editcommit.php
> +        if (!defined('DOKU_FARM') && $repoPath[0] !== '/') {
makes sense. I don't fully understand your proposed approach using the abs path function. could you provide a snippet?

2022-08-12 12:48 UTC, mhoffrog commented on action/editcommit.php
> +        if (!defined('DOKU_FARM') && $repoPath[0] !== '/') {
something like:

`$repoPath = $this->getConf('repoPath');`
`$is_absolute_path = $repoPath == realpath($repoPath);`

2022-08-13 08:44 UTC, mhoffrog commented on action/editcommit.php
> +        if (!defined('DOKU_FARM') && $repoPath[0] !== '/') {
@woolfg @sjv0 Having looked how DokuWiki does absolute path determination - probably this would be an applicable solution - using the same implementation as the original DokuWiki `init.php` does in method `fullpath(...)` (DokuWiki release Hogfather):
```php
/**
 * This function behaves like absolute path determination in dokuwiki init.php fullpath() method.
 * The relevant code has been copied from there.
 *
 * @param string $path
 *
 * @return bool
 */
function isAbsolutePath($path){
    $ret  = false;
    $iswin = (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN' || !empty($GLOBALS['DOKU_UNITTEST_ASSUME_WINDOWS']));

    // check for the (indestructable) root of the path - keeps windows stuff intact
    if($path[0] == '/'){
        $ret = true;
    }elseif($iswin){
        // match drive letter and UNC paths
        if(preg_match('!^([a-zA-z]:)(.*)!',$path,$match)){
            $ret = true;
        }else if(preg_match('!^(\\\\\\\\[^\\\\/]+\\\\[^\\\\/]+[\\\\/])(.*)!',$path,$match)){
            $ret = true;
        }
    }
    return $ret;
}
```

2023-02-09 00:13 UTC, mhoffrog approved these changes
Approved. Additional code changes required have been provided by https://github.com/woolfg/dokuwiki-plugin-gitbacked/commit/dee8dca12468216679c058a7a0a707e74e351cfa

2023-02-09 00:39 UTC, mhoffrog commented
Closing this PR, since it is integrated part of Pr #83.

2023-02-09 00:39 UTC, closed without merging